### PR TITLE
Fix: Metro configs updated in order to enable watcher and debugging on native apps

### PR DESCRIPTION
**Pull request by infreezer**
When updating react native to version 0.59.x the metro configs used were changed.
The change blocked the debugging and disable the watchers (hot reloading)
The ios app, android app and storybook-native were affected.
In this PR I'm updating the scripts in package.json to use the working metro configs and removing the unused configs.

### CODE REVIEW

**Comment by parkjh** [comment]
> When updating react native to version 0.59.x the metro configs used were changed.
> The change blocked the debugging and disable the watchers (hot reloading)
> The ios app, android app and storybook-native were affected.
> In this PR I'm updating the scripts in package.json to use the working metro configs and removing the unused configs.

@infreezer hmm these changes actually fixed hot reloading for me... this was also confirmed when it was first upgraded by tunca... https://github.com/newsuk/times-components/pull/1931/files

**Comment by parkjh** [comment]
can anyone else confirm that this doesn't work?

**Comment by infreezer** [comment]
> > When updating react native to version 0.59.x the metro configs used were changed.
> > The change blocked the debugging and disable the watchers (hot reloading)
> > The ios app, android app and storybook-native were affected.
> > In this PR I'm updating the scripts in package.json to use the working metro configs and removing the unused configs.
> 
> @infreezer hmm these changes actually fixed hot reloading for me... this was also confirmed when it was first upgraded by tunca... https://github.com/newsuk/times-components/pull/1931/files

Please check this PR: [https://github.com/newsuk/times-components/pull/2047](https://github.com/newsuk/times-components/pull/2047)

**Comment by parkjh** [comment]
@infreezer nice one!

**Pull request merged**
