### PR TITLE
fix: Update video attribute

### PR DESCRIPTION
**Pull request by nehasri89**

### CODE REVIEW

**Comment by aronshamash** [comment]
I think there should be some snapshots to update and maybe fixtures too.

**Comment by colincclark** [comment]
what does this do?

**Comment by nikhedonia** [comment]
Apparently the schema changed:
https://github.com/newsuk/times-public-api/pull/354/commits/b9d560464786bab4c58bb246220a3f4f79890c3e

Is anybody relying on the old schema with `paidonly` ?
If so we need to deprecate it first before we can rename it.

**Comment by nehasri89** [comment]
@nikhedonia - no, only TC is consuming it atm

**Comment by nehasri89** [comment]
@colincclark - This is to align it to the latest tpa changes for video. @aronshamash - fixtures updated

**Pull request merged**
