### PR TITLE
chore: bump yarn to 1.5.1

### PR DESCRIPTION
**Pull request by craigbilner**

### CODE REVIEW

**Comment by aronshamash** [comment]
I've updated to yarn `1.5.1` and checked this branch locally and I'm getting the following error in the console when running `yarn storybook`

screen shot 2018-03-12 at 10 07 24

**Comment by jimhunty** [comment]
@aronshamash I have rebased and pushed this. It now works fine for me.

**Comment by aronshamash** [comment]
I'll check now

**Comment by aronshamash** [comment]
Check storybook locally and all is good.

**Pull request merged**
