### PR TITLE
Add basic pagination footer to author profile

### PR DESCRIPTION
**Pull request by trevorah**
Its not the prettiest, but its something we can improve.

screen shot 2017-09-29 at 09 38 41

sep-29-2017 09-37-10

I've also removed "page" from the controls, just to make it a little bit closer to the mockups (https://app.zeplin.io/project/59a6a2c092fb8c2b6944c504/screen/59a6a3120f46b28066f67eca).

### CODE REVIEW

**Comment by sericaia** [comment]
@trevorah  A file named `example.json` is in provider package and it's used here in `packages/provider/__tests__/__snapshots__/author-profile-provider.test.js.snap`.  Would you mind to move it into a folder called `fixtures` and give it an appropriate name (`author-profile.json`)?

**Comment by sericaia** [comment]
I just moved it here https://github.com/newsuk/times-components/pull/262/files

**Comment by trevorah** [comment]
@sericaia can do!

**Comment by trevorah** [comment]
@sericaia if you've already moved it, I wont touch it in this branch.

**Pull request merged**
