### PR TITLE
chore: added code owners

### PR DESCRIPTION
**Pull request by parkjh**

### CODE REVIEW

**Comment by parkjh** [comment]
@nehasri89 @aronshamash @Belema @nathggns @jimhunty 
I've added your newsuk email addresses, which means that for it to work your associated github account needs to have the same newsuk emails...

**Comment by tuncaulubilge** [comment]
:(

**Comment by colincclark** [comment]
👎

**Comment by aronshamash** [comment]
Why will it not work with my current email address associated with github account ?

**Comment by parkjh** [comment]
@aronshamash because that should be the email address that the github assigns account to. And the reason that it's newsuk email is probably to ensure that all the codeowners are still employee here? I'm not sure, but I have not heard any good argument against and it seems sensible to me...

**Comment by parkjh** [comment]
@colincclark @tuncaulubilge feel free to volunteer to be code owner~~~

**Pull request merged**
