### PR TITLE
Feat/edition slices strapline override

### PR DESCRIPTION
**Pull request by apostolnikov**
Strapline override added.

https://nidigitalsolutions.jira.com/secure/RapidBoard.jspa?rapidView=978&projectKey=REPLAT&modal=detail&selectedIssue=REPLAT-5877

### CODE REVIEW

**Comment by aronshamash** [comment]
@apostolnikov Can we have a snapshot test for this logic?

**Comment by nehasri89** [comment]
@apostolnikov needs to add this field in `article` queries in this package `https://github.com/newsuk/times-components/tree/master/packages/provider-queries` and update corresponding test

**Comment by tuncaulubilge** [comment]
You need to update `section-fragment` query in provider-queries. We already have strapline field in `tile` segment of that query, you'll need to add the same thing into the `article` for those tiles

**Comment by nehasri89** [comment]
needs a test here to test the override `https://github.com/newsuk/times-components/blob/master/packages/edition-slices/__tests__/shared-components.base.js`

**Pull request merged**
