### PR TITLE
chore: improve slice layout tc

### PR DESCRIPTION
**Pull request by ValGeorgiev**
Refactor slice-layouts proptypes
Improve test coverage to 100%
Minimize the slice-layout package with 5kb. Small steps for faster web :D

### CODE REVIEW

**Comment by nathggns** [comment]
This is a *huge* PR. Can you please elaborate on what it's doing, how it's doing it, what the purpose is, and what we should look for in the changes?

**Comment by ValGeorgiev** [comment]
Thanks for the comment @nathggns 

1. This is fixing the wrong snapshots for some of the slice-layout mobile. Because previously we didn't have default props for breakpoint and slice layout for mobile was the same as medium snapshot

2. Removing unnecessary additional prop-types files, this is saving 4kb from slice-layout package

3. Moving roles to the related articles package, because they are used only there for tracking

4. adding additional tests to improve test coverage in slice-layout to 100%. This is the first pr, we will do more for almost every package. We want 100% coverage 

Let me know if I need to provide more info

**Comment by parkjh** [comment]
> Thanks for the comment @nathggns
> 
>     1. This is fixing the wrong snapshots for some of the slice-layout mobile. Because previously we didn't have default props for breakpoint and slice layout for mobile was the same as medium snapshot
> 
>     2. Removing unnecessary additional prop-types files, this is saving 4kb from slice-layout package
> 
>     3. Moving roles to the related articles package, because they are used only there for tracking
> 
>     4. adding additional tests to improve test coverage in slice-layout to 100%. This is the first pr, we will do more for almost every package. We want 100% coverage
> 
> 
> Let me know if I need to provide more info

doesn't this require another full demo of all the tablet section, given that this touches all of them?

**Comment by ValGeorgiev** [comment]
> > Thanks for the comment @nathggns
> > ```
> > 1. This is fixing the wrong snapshots for some of the slice-layout mobile. Because previously we didn't have default props for breakpoint and slice layout for mobile was the same as medium snapshot
> > 
> > 2. Removing unnecessary additional prop-types files, this is saving 4kb from slice-layout package
> > 
> > 3. Moving roles to the related articles package, because they are used only there for tracking
> > 
> > 4. adding additional tests to improve test coverage in slice-layout to 100%. This is the first pr, we will do more for almost every package. We want 100% coverage
> > ```
> > 
> > 
> > Let me know if I need to provide more info
> 
> doesn't this require another full demo of all the tablet section, given that this touches all of them?

I didn't touch any of the components, I only migrate proptypes from one file to another and add more tests :)

**Comment by parkjh** [comment]
> > > Thanks for the comment @nathggns
> > > ```
> > > 1. This is fixing the wrong snapshots for some of the slice-layout mobile. Because previously we didn't have default props for breakpoint and slice layout for mobile was the same as medium snapshot
> > > 
> > > 2. Removing unnecessary additional prop-types files, this is saving 4kb from slice-layout package
> > > 
> > > 3. Moving roles to the related articles package, because they are used only there for tracking
> > > 
> > > 4. adding additional tests to improve test coverage in slice-layout to 100%. This is the first pr, we will do more for almost every package. We want 100% coverage
> > > ```
> > > 
> > > 
> > > Let me know if I need to provide more info
> > 
> > 
> > doesn't this require another full demo of all the tablet section, given that this touches all of them?
> 
> I didn't touch any of the components, I only migrate proptypes from one file to another and add more tests :)

can you please make sure that all the snapshots are correct? especially ones that are not additive but alters the existing snapshot? because if that's true then non of the existing snapshot should've changed at all...

**Comment by ValGeorgiev** [comment]
> > > > Thanks for the comment @nathggns
> > > > ```
> > > > 1. This is fixing the wrong snapshots for some of the slice-layout mobile. Because previously we didn't have default props for breakpoint and slice layout for mobile was the same as medium snapshot
> > > > 
> > > > 2. Removing unnecessary additional prop-types files, this is saving 4kb from slice-layout package
> > > > 
> > > > 3. Moving roles to the related articles package, because they are used only there for tracking
> > > > 
> > > > 4. adding additional tests to improve test coverage in slice-layout to 100%. This is the first pr, we will do more for almost every package. We want 100% coverage
> > > > ```
> > > > 
> > > > 
> > > > Let me know if I need to provide more info
> > > 
> > > 
> > > doesn't this require another full demo of all the tablet section, given that this touches all of them?
> > 
> > 
> > I didn't touch any of the components, I only migrate proptypes from one file to another and add more tests :)
> 
> can you please make sure that all the snapshots are correct? especially ones that are not additive but alters the existing snapshot? because if what you say is true then non of the existing snapshot should've changed at all...

Please check the first point in my explanation. `1. This is fixing the wrong snapshots for some of the slice-layout mobile. Because previously we didn't have default props for breakpoint and slice layout for mobile was the same as medium snapshot`

**Comment by parkjh** [comment]
@ValGeorgiev I feel that the new snapshot tests are fine and can go in separately... but not sure of the need to move the proptyes?

**Comment by nathggns** [comment]
I feel like this PR should be split up tbh. It's doing separate things and some of the changes could be masking issues in others.

**Comment by infreezer** [comment]
> @ValGeorgiev I feel that the new snapshot tests are fine and can go in separately... but not sure of the need to move the proptyes?

When the proptypes are in separate file. The lint isn't working for me.

**Comment by parkjh** [comment]
> > @ValGeorgiev I feel that the new snapshot tests are fine and can go in separately... but not sure of the need to move the proptyes?
> 
> When the proptypes are in separate file. The lint isn't working for me.

@infreezer can you please clarify what linting error you are getting? because currently on master all the proptypes are in separate file and they seem fine?

**Comment by infreezer** [comment]
> > > @ValGeorgiev I feel that the new snapshot tests are fine and can go in separately... but not sure of the need to move the proptyes?
> > 
> > 
> > When the proptypes are in separate file. The lint isn't working for me.
> 
> @infreezer can you please clarify what linting error you are getting? because currently on master all the proptypes are in separate file and they seem fine?

The issue is that it looks like everything is fine, because there are no errors. No matter what are the proptypes.
There are a lot of examples:
Pick the first slice in slice-layout - let's say commentleadandcartoon.
Any change in the proptypes doesn't trigger an error and I know there should be. Still passes after lint.
In the example slice when the proptypes are in separate file the error: 'breakpoint' is missing in props validation is not received.

**Pull request merged**
