### PR TITLE
fix/coveralls

### PR DESCRIPTION
**Pull request by dickie81**
Fixes coverage paths. Also removes redundant yarn.lock

### CODE REVIEW

**Comment by damnhipster** [comment]
When I added `babel-jest`, I only saw a [few changes in `yarn.lock`](https://github.com/newsuk/times-components/commit/7383c677921a3a8a06d79b5c077ea2c326086ab9#diff-8ee2343978836a779dc9f8d6b794c3b2). Are the rest of the changes needed?

**Comment by damnhipster** [comment]
To be honest, I think it's worth merging in minor upgrades like this as part of PRs, since it's pretty low risk.

**Comment by dickie81** [comment]
Coverage re-instated.

`author-profile` still reports coverage as unknown. It was fixed and working at this commit; https://github.com/newsuk/times-components/pull/406/commits/e81777744c6c757d356b23cf11f233a5f1082bf6. The only way I could get this working was to remove `jest-cli` from the `author-profile` & add `babel-jest` to every package. Updating `jest-cli` to stop the message regarding upgrading `jest` broke everything.

**Comment by dickie81** [comment]
@craigbilner when you say remove do you mean restore?

**Comment by dickie81** [comment]
or remove removing?

**Pull request merged**
