### PR TITLE
Update to react-native 0.49 and react 16

### PR DESCRIPTION
**Pull request by killanaca**
EDIT 1: update to react-native 0.48.4 and react-native-web 0.1.0
EDIT 2: update to react-native 0.49.0 and react-native-web 0.1.3
EDIT 3: update to react-native 0.49.3 and react-native-web 0.1.7

**Updated deps**
- react-native: 0.42.3 -> 0.49.3
- react: 15.4.2 -> 16.0.0
- react-dom 15.4.2 -> 16.0.0
- react-native-web 0.0.119 -> 0.1.7
- react-test-renderer 15.4.2 -> 16.0.0
- react-native-storybook-loader: 1.4.1 -> 1.5.1
- prop-types 15.5.10 -> 15.6.0 
- jest 20.0.4 -> 21.2.1
- enzyme 2.9.1 -> 3.1.0 [Migration Guide for enzyme v2.x to v3.x]( https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md)
- enzyme-adapter-react 16 1.0.1 (NEW)
- enzyme-to-json 1.5.1 -> 3.1.0
- react-addons-test-utils (REMOVED) -> react-dom/test-utils
- svg 2.3.0 -> 3.1.0
- react-native-svg 5.1.7 -> 5.4.1

**iOS**
- new native library `libRCTBlob` added (in v0.48.0)
- move scripts from packager to scripts folder

**Enzyme**
With Enzyme 3:
- new Adapter system to deal with different versions of React and other frameworks (Preact, Inferno..)
- new format for the snapshot

**React Addons Test Utils**
No more `react-addons-test-utils` lib, use instead `react-dom/test-utils`

**Jest**
Jest v21 snapshots handle whitespace differently

**Warning**
Using `<Image>`with children is [deprecated]( https://github.com/facebook/react-native/commit/9637dd4a1b78d5f6da510b1b4ad10d45d67badbf)
`<ListView>` is [deprecated](https://facebook.github.io/react-native/docs/listview.html)

**Master branch**
Done in 138.95s.
real	2m19.261s
user	5m6.292s
sys	0m17.313s

**This branch**
Done in 274.23s.
real	4m34.540s
user	5m1.409s
sys	2m1.216s

### CODE REVIEW

**Comment by sericaia** [comment]
This code is fine and fixes the android issue 👍 
image

The only issue that still remains is this one https://github.com/necolas/react-native-web/issues/669

**Comment by rjanjua** [comment]
the bitrise job is failing because it seems detox is not ready for React 16 - the failure is not genuine. We need to check that everything works in storybook and storybook-native

**Comment by aronshamash** [comment]
I have checked through web, ios and android and the component functionality has not regressed as far as I can see.

**Comment by sericaia** [comment]
In order to fix the android issue 

```
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

I deleted `android/.gradle` folder and after running `yarn android` it was generated again and everything worked fine

**Comment by killanaca** [comment]
seems like we need for this issue to be closed https://github.com/wix/detox/issues/279

**Comment by sericaia** [comment]
Getting this now:
image

**Comment by JGAntunes** [comment]
Tested it in web (chrome and IE11) and Android and spotted no regressions :+1:

**Pull request merged**
