### PR TITLE
chore: remove flowtype eslint preset

### PR DESCRIPTION
**Pull request by parkjh**

### CODE REVIEW

**Comment by ValGeorgiev** [comment]
Could you add more description why you are removing that, please? We need to agree on such changes, if you describe why you are removing it and what benefits you see, it will be enough. Thanks

**Comment by parkjh** [comment]
> Could you add more description why you are removing that, please? We need to agree on such changes, if you describe why you are removing it and what benefits you see, it will be enough. Thanks

we do not use flow...

**Comment by ValGeorgiev** [comment]
> > Could you add more description why you are removing that, please? We need to agree on such changes, if you describe why you are removing it and what benefits you see, it will be enough. Thanks
> 
> we do not use flow...

I am talking overall for all chore PRs

**Comment by parkjh** [comment]
> > > Could you add more description why you are removing that, please? We need to agree on such changes, if you describe why you are removing it and what benefits you see, it will be enough. Thanks
> > 
> > 
> > we do not use flow...
> 
> I am talking overall for all chore PRs

will do

**Comment by parkjh** [comment]
@jmars text-flow packages has a lot of `error  Parsing error: Unexpected token =` issues...

**Pull request merged**
