### PR TITLE
fix: Padding on the link instead of outside it

### PR DESCRIPTION
**Pull request by jimhunty**
This is part of the design snag list, detailed here: https://nidigitalsolutions.jira.com/browse/REPLAT-3472

### CODE REVIEW

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/596d06e06b08f9de1ff3a0da30923d27c60a59d6/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/a48446eacd360ac67472c801f0a89231229ff8db/index.html

**Comment by aronshamash** [comment]
could you add a before and after screenshot ?

**Comment by jimhunty** [comment]
@aronshamash Dextrose provides the screenshots.

**Pull request merged**
