### PR TITLE
Fix: Lead asset pixel bug

### PR DESCRIPTION
**Pull request by aronshamash**
- Fixes issue with 1px white line above lead asset on in depth articles. https://nidigitalsolutions.jira.com/browse/REPLAT-6628
- move `resizeMode="contain"` from style to the `image` component.

## iOS app

Screenshot 2019-07-05 at 12 25 11

### CODE REVIEW

**Comment by nathggns** [comment]
Have you tested how this impacts modal images (specifically, portrait modal images)?

**Comment by aronshamash** [comment]
> Have you tested how this impacts modal images (specifically, portrait modal images)?

@nathggns I tested but let me double check and post a screenshot to be sure

**Comment by aronshamash** [comment]
> > Have you tested how this impacts modal images (specifically, portrait modal images)?
> 
> @nathggns I tested but let me double check and post a screenshot to be sure

So there is no regression when comparing this branch against `master` both show a white Times `T` and no image is shown. Is this a bug?

**Comment by aronshamash** [comment]
close PR until tested in storybook working with modals

**Pull request closed without merging**
