### PR TITLE
Fix/tracking display name

### PR DESCRIPTION
**Pull request by tuncaulubilge**
Analytics component name requires component displayName, which in turn requires
babel-plugin-add-react-displayname to be able to fetch display name on release builds

Updated peer dependencies
Updated contributing docs

### CODE REVIEW

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/e36ae02f87f77a24b17921affea7e3938818bc96/dextrose-test/index.html

**Comment by colincclark** [comment]
@tuncaulubilge is this related to https://github.com/newsuk/times-components/blob/master/packages/tracking/tracking-context.js#L13 ?

**Comment by tuncaulubilge** [comment]
@colincclark Yes it is, component.displayName is Unknown on release builds if we don't have this babel plugin

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/56f3a0c0291ce63752bd50b225e5ce89151c3453/dextrose-test/index.html

**Pull request merged**
