### PR TITLE
feat: upgrade RN to 0.55.4

### PR DESCRIPTION
**Pull request by colincclark**
Note: this is dependent on fructose being bumped to the same version of RN (see image)

screen shot 2018-06-07 at 16 10 37

### CODE REVIEW

**Comment by tuncaulubilge** [comment]
Why don't we go for 0.55.4?

**Comment by L0wry** [comment]
if we bump to this version we will lose the ability for expo to work due to this being an unsupported version.
the latest version of RN supported by expo is 0.54
https://blog.expo.io/expo-sdk-v27-0-0-is-now-available-898bf1e5b0e4 


@craigbilner your call

**Comment by craigbilner** [comment]
looks like there's some issues on Bitrise anyway.

@colincclark if you can spike it out to find out what it takes to get to the latest version to make it easy when we get there, it would be ideal if we watch [this space](https://github.com/expo/expo/milestone/18) so our tooling supports what we're shipping

**Comment by colincclark** [comment]
Bitrise issues are related to the competing RN versions with fructose

**Comment by craigbilner** [comment]
closing while @L0wry investigates

**Pull request closed without merging**
