### PR TITLE
chore: Max number of Article Topics to 5

### PR DESCRIPTION
**Pull request by jimhunty**
On an article, the maximum number of Article Topics shown can be 5. This enforces this.

### CODE REVIEW

**Comment by craigbilner** [comment]
@jimhunty should this not be a provider/TPA change? Also it would be ideal if the diff didn't change (by adding the additional topic at the end)?

**Comment by jimhunty** [comment]
@craigbilner Putting the max number of topics on TPA restricts the API for other consumers?

**Comment by craigbilner** [comment]
@jimhunty didn't mean hard code it!
@aronshamash yes, the consumer should be able to request the topics they would like, the client shouldn't have to handle the data per se

**Comment by jimhunty** [comment]
Why was this closed @craigbilner? Can you give more information on what you mean by `take` ?

**Comment by jimhunty** [comment]
Alternative approach will be taking by paging topics from TPA as discussed with @craigbilner

**Pull request closed without merging**
