### PR TITLE
fix: browser issue

### PR DESCRIPTION
**Pull request by sericaia**
image
From left to right: chrome, FF, safari

image
From left to right: android, ios

### CODE REVIEW

**Comment by sericaia** [comment]
Do not merge yet

**Comment by jimhunty** [comment]
Its not what I would use `display: table` for but works well, so its a 👍 from me.

**Comment by sericaia** [comment]
@jimhunty i could not find another way to solve this issue in FF

**Comment by damnhipster** [comment]
We should be able to use a `clearfix` for this issue.

I'll give it a try.

**Pull request merged**
