### PR TITLE
Feat: slices 1024px

### PR DESCRIPTION
**Pull request by ValGeorgiev**
Merge slices-1024px to master

### CODE REVIEW

**Comment by infreezer** [comment]
tile-r/styles/index.js should look like:
https://github.com/newsuk/times-components/blob/6268e69bd2362d97fb80e5ca3cb2fcb711937999/packages/edition-slices/src/tiles/tile-r/styles/index.js

**Comment by infreezer** [comment]
tile-u/styles.js final version should be:
https://github.com/newsuk/times-components/blob/6268e69bd2362d97fb80e5ca3cb2fcb711937999/packages/edition-slices/src/tiles/tile-u/styles/index.js

**Comment by ValGeorgiev** [comment]
comments are addressed

**Comment by parkjh** [comment]
> comments are addressed

@ValGeorgiev I understand that these changes were broken up and done in separate prs but with this many styles changes I would prefer to have it QA'd on a device... I don't think each pr screenshots are quite sufficient?

**Comment by ValGeorgiev** [comment]
> @ValGeorgiev I understand that these changes were broken up and done in separate prs but with this many styles changes I would prefer to have it QA'd on a device... I don't think each pr screenshots are quite sufficient?

We did manual testing yesterday and today as well. We have several more scenarios to check, thats why we don't merge it yet. We need several minutes and we will merge it before lunch.

**Comment by infreezer** [comment]
tile-ah/styles.js missing styling. Please use:
https://github.com/newsuk/times-components/blob/6268e69bd2362d97fb80e5ca3cb2fcb711937999/packages/edition-slices/src/tiles/tile-ah/styles/index.js

**Comment by parkjh** [comment]
> > @ValGeorgiev I understand that these changes were broken up and done in separate prs but with this many styles changes I would prefer to have it QA'd on a device... I don't think each pr screenshots are quite sufficient?
> 
> We did manual testing yesterday and today as well. We have several more scenarios to check, thats why we don't merge it yet. We need several minutes and we will merge it before lunch.

@ValGeorgiev I think it would be helpful to have a list of scenarios that you guys manually tested?

**Comment by ValGeorgiev** [comment]
> > > @ValGeorgiev I understand that these changes were broken up and done in separate prs but with this many styles changes I would prefer to have it QA'd on a device... I don't think each pr screenshots are quite sufficient?
> > 
> > 
> > We did manual testing yesterday and today as well. We have several more scenarios to check, thats why we don't merge it yet. We need several minutes and we will merge it before lunch.
> 
> @ValGeorgiev I think it would be helpful to have a list of scenarios that you guys manually tested?

These are only changes in tiles and slices, we are going through all of them on android and ios, to see if changes are not messed up. Changes are only visual :)

**Comment by parkjh** [comment]
> > > > @ValGeorgiev I understand that these changes were broken up and done in separate prs but with this many styles changes I would prefer to have it QA'd on a device... I don't think each pr screenshots are quite sufficient?
> > > 
> > > 
> > > We did manual testing yesterday and today as well. We have several more scenarios to check, thats why we don't merge it yet. We need several minutes and we will merge it before lunch.
> > 
> > 
> > @ValGeorgiev I think it would be helpful to have a list of scenarios that you guys manually tested?
> 
> These are only changes in tiles and slices, we are going through all of them on android and ios, to see if changes are not messed up. Changes are only visual :)

hence my point that we need this to be QA'd, no?

**Comment by parkjh** [comment]
I mean I suppose I would've been happy with each individual prs getting merged due to the small impact... but with this I'm not so confident but it may be just me

**Comment by ValGeorgiev** [comment]
@parkjh Every one commit in this branch is tested and demonstrated to Kumaran and UI/UX people, they are happy with these changes and they want us to merge it. I don't want to loose more time in separating every pr in separate one :)

**Comment by parkjh** [comment]
> @parkjh Every one commit in this branch is tested and demonstrated to Kumaran and UI/UX people, they are happy with these changes and they want us to merge it. I don't want to loose more time in separating every pr in separate one :)

sorry which UI/UX people?

**Comment by infreezer** [comment]
> Just finished with visually checking all the slices on iPad simulator. After tile-ah styling is updated it can be merged.

**Pull request merged**
