### PR TITLE
fix: the next/previous page styling

### PR DESCRIPTION
**Pull request by rjanjua**
This PR fixes the styling of the next and previous page icons in the pagination component.

Checked everything in storybook, and storybook native on all platforms.

### Android
screen shot 2017-10-06 at 15 13 03

### iOS
screen shot 2017-10-06 at 15 12 25

### browser - narrow
screen shot 2017-10-06 at 15 10 59

### browser - wide
screen shot 2017-10-06 at 15 11 14

### CODE REVIEW

**Comment by trevorah** [comment]
iOS needs a tweak, and dont worry about having duplicate svg markup.

**Comment by rjanjua** [comment]
### iOS
screen shot 2017-10-06 at 16 03 31

### android 
screen shot 2017-10-06 at 16 08 17

### web narrow
screen shot 2017-10-06 at 16 03 46

### web wide
screen shot 2017-10-06 at 16 03 57

**Comment by rjanjua** [comment]
side by side ios pre and post last commit:
screen shot 2017-10-06 at 15 12 25
pre-commit
screen shot 2017-10-06 at 16 03 31
post-commit

**Comment by trevorah** [comment]
https://github.com/newsuk/times-components/pull/277 was merged instead.

**Pull request closed without merging**
