### PR TITLE
chore: remove react art

### PR DESCRIPTION
**Pull request by parkjh**
Screenshot 2019-05-16 at 14 58 04

### CODE REVIEW

**Comment by parkjh** [comment]
need on device testing but on android sim it seems ok...? @tuncaulubilge

**Comment by tuncaulubilge** [comment]
What about svgs on web?

**Comment by parkjh** [comment]
> What about svgs on web?

checked on storybook web, I will post a screenshot but it seems ok...? was there any specific page that you wanted me to have a look?

**Comment by parkjh** [comment]
> What about svgs on web?

see the above screenshot...

**Comment by nathggns** [comment]
Have you checked that gradients on sky sports videos and on image modals still work?

**Comment by parkjh** [comment]
> Have you checked that gradients on sky sports videos and on image modals still work?

seems ok to me? I compared it to https://components-preview.thetimes.co.uk/?knob-Size%20of%20ad%20placeholder%3A=default&selectedKind=Primitives%2FVideo&selectedStory=skysports%20video&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs

Screenshot 2019-05-16 at 16 52 36

**Comment by parkjh** [comment]
this pr needs testing with local render to double check...

**Comment by nathggns** [comment]
@parkjh what about modal images? The caption has a gradient behind it on iOS.

**Comment by parkjh** [comment]
> @parkjh what about modal images? The caption has a gradient behind it on iOS.

well iOS hot reloading does not work...

**Comment by tuncaulubilge** [comment]
> > @parkjh what about modal images? The caption has a gradient behind it on iOS.
> 
> well iOS hot reloading does not work... was it iOS specific? or can I test it on other platform?

iOS storybook does work, you can test there

**Pull request closed without merging**
