### PR TITLE
Chore/a11y Add accessibility checks to storybook

### PR DESCRIPTION
**Pull request by aronshamash**
Adds an accessibility addon to storybook which highlights accessibility issues in the component stories. https://github.com/newsuk/times-components/issues/677

### CODE REVIEW

**Comment by jimhunty** [comment]
Can the decorator be added at the config so it will be applied to all stories? Do we want it on all stories? Does this work with React Native as well?

**Comment by aronshamash** [comment]
@jimhunty Move to storybook config. I think they should be on any component with a UI. Its doesn't work on native.

**Comment by aronshamash** [comment]
Found to not work with React Native

**Comment by craigbilner** [comment]
@aronshamash how does the `checkA11y` work now?

**Comment by aronshamash** [comment]
@craigbilner it didn't work and I have had to add the decorator in each story we would like a11y checks.

**Comment by jimhunty** [comment]
This should be added to the CLI?

**Comment by aronshamash** [comment]
@jimhunty Added to cli

**Pull request merged**
