### PR TITLE
(Replat 6411) turn on clipsubviews for flatlists

### PR DESCRIPTION
**Pull request by jmars**
Just adds the clipsubviews parameter to flatlists, it is off by default because it can cause some rendering issues but I don't see any on our components and it's an easy win for memory usage.

### CODE REVIEW

**Comment by parkjh** [comment]
https://facebook.github.io/react-native/docs/flatlist#removeclippedsubviews
`Note: May have bugs (missing content) in some circumstances - use at your own risk.`

**Comment by nathggns** [comment]
Think we need conventional commits on either the commits or the PR title right?

**Comment by tuncaulubilge** [comment]
Title should be conventional commit, but you can change it while squashing

**Comment by nehasri89** [comment]
@jmars have we tested on real device ?

**Comment by jmars** [comment]
I have tested this on the beast/slow devices and it does cause any regressions

**Pull request merged**
