### PR TITLE
chore: remove legacy babel

### PR DESCRIPTION
**Pull request by parkjh**

### CODE REVIEW

**Comment by nehasri89** [comment]
have you ran ssr after this changeb to test?

**Comment by parkjh** [comment]
> have you ran ssr after this change to test?

ssr passes locally

**Comment by parkjh** [comment]
@jmars hmm this should not have worked... but seems ok here https://github.com/newsuk/cps-content-render/pull/2871

**Comment by parkjh** [comment]
react native web supported babel 7
https://github.com/necolas/react-native-web/commit/77d4bd8a9732fbfba519066ae24fa4ae93b15f6d

**Pull request merged**
