### PR TITLE
fix: correcting app delegate to support release and dev configuration

### PR DESCRIPTION
**Pull request by kaliabadi**
This change allows for both release and debug variants of the storybook app.

I thinkt here was some confusion as we are sharing this app delegate file and some of my changes had been reverted.

I have tested this change and it works for both sotrybook native and dextrose ios.

### CODE REVIEW

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by kaliabadi** [comment]
testy test

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/4c0ee7dff033fe2bba9535a53bdfdf7957bd331f/dextrose-test/index.html

**Pull request merged**
