### PR TITLE
Fix/bio width

### PR DESCRIPTION
**Pull request by foliveira**
**Web:**
web

**Mobile:**
mobile

**iPhone:**

iphone

**Android:**

android

### CODE REVIEW

**Comment by trevorah** [comment]
@foliveira looks good! How does it look on iOS and Android?

**Comment by fampinheiro** [comment]
@trevorah the native images were already uploaded.

**Comment by craigbilner** [comment]
@foliveira if we're following the web, < 768px is left aligned?

**Comment by foliveira** [comment]
@craigbilner the change you mentioned could be easily implemented with the responsive stylesheets feature I'm working on, i.e.: it would avoid spreading checks for the width in components.

Can we move to that once that feature lands?

**Pull request merged**
