### PR TITLE
feat(TMRX-1462): added data-testids to required components

### PR DESCRIPTION
**Pull request by nishprogrammes**
### Description

Experimentation team wish to track click events on the following buttons;

 * Play
 * Pause
 * Feedback

To aid this they have requested we add data-testids to each button

[JIRA-1462](https://nidigitalsolutions.jira.com/browse/TMRX-1462)

### Checklist

- [x] Have you done any manual testing?
- [ ] Does it have automated tests?
- [ ] Do you need any other PRs merged before this (if so please list)?
- [ ] Do you need to update the README/Runbook
- [ ] Have you checked for [accessibility](https://nidigitalsolutions.jira.com/wiki/spaces/TNLDigital/pages/3898048523/Accessibility+Dev+Guide#Checklist)?

### CODE REVIEW

**Review by bibicollins1 — COMMENTED** [review]
Just wondering on the ticket it mentions play and pause, I can't see those changes here?

**Comment by nishprogrammes** [comment]
> Just wondering on the ticket it mentions play and pause, I can't see those changes here?

@bibicollins1 The newskit components already have the testid on them. I have left a comment in the JIRA ticket.

**Review by douglasmik — COMMENTED** [review]
Also need test id's added to 'Play/Pause' buttons. Will possible need to add logic to toggle values, as has been done for button labels. This will also need to be done in the 'sticky player' files

**Comment by nishprogrammes** [comment]
@douglasmik I have added the conditional logic. Can you please review again?

**Review by douglasmik — APPROVED** [review]

**Review by ibrahim-kurhan — APPROVED** [review]

**Pull request merged**
