### PR TITLE
feat/brightcove-ios-direct-to-fullscreen

### PR DESCRIPTION
**Pull request by dickie81**
Implements direct to fullscreen for iOS:

Exposes native module with same API used for Android direct to fullscreen. API method `playVideo(VIDEO_PROPS)` launches new view controller meaning video player is rendered outside ReactRoot.

This behaviour is triggered by adding `directToFullscreen` property to `brightcove-video` component.

### CODE REVIEW

**Comment by trevorah** [comment]
@dickie81 @mabidakun do you know why the tests are failing?

**Comment by trevorah** [comment]
Also, can you add some details to the description?

**Comment by dickie81** [comment]
Description updated.

**Comment by trevorah** [comment]
Wait, all the objective c is in the storybook dir rather than the package. How is this going to be distributed?

**Pull request merged**
