### PR TITLE
fix: replat 6568 remove memoize

### PR DESCRIPTION
**Pull request by parkjh**

### CODE REVIEW

**Comment by nathggns** [comment]
Please don't merge this until we've discussed it more – this was added for a reason and there may be alternative ways to address the bug.

**Comment by parkjh** [comment]
> Please don't merge this until we've discussed it more – this was added for a reason and there may be alternative ways to address the bug.

hence this is a draft so far...

**Comment by nathggns** [comment]
Sure. That comment isn't for you, its for others.

**Comment by parkjh** [comment]
@nathggns did you manage to test this further yesterday?

**Comment by parkjh** [comment]
closing after discussion with @nathggns

**Pull request closed without merging**
