### PR TITLE
Fix: Lead 2 no pic and 2 order

### PR DESCRIPTION
**Pull request by aronshamash**
- https://nidigitalsolutions.jira.com/browse/TNLT-2436
- Order of articles was incorrect compared to web. The below screenshots are after this fix and show that order matches web for medium and wide breakpoints.

### Portrait
Screenshot 2020-06-17 15 22 44

### Landscape
Screenshot 2020-06-17 15 23 15

### CODE REVIEW

**Comment by infreezer** [comment]
Do we have to show summary for support1
image

**Comment by aronshamash** [comment]
> Do we have to show summary for support1
> and remove it for support2 if we are using web for reference
> 
> image

TILE E : has summary text
TILE AL: doesn't have summary text

maybe we can't just switch the order of the Tiles. I'll ask the designer.

**Comment by aronshamash** [comment]
@infreezer is there google doc or zeplin detailing the tiles needed in each slice at each breakpoint ?

**Comment by infreezer** [comment]
> @infreezer is there google doc or zeplin detailing the tiles needed in each slice at each breakpoint ?

[Zeplin ](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d6e699c627d5218b711028c)
[Slices docs](https://docs.google.com/spreadsheets/d/1NBC-dOAGcF1sgfrkfFH7uslKG7eEU4o3n3Og5T1WNC8/edit#gid=255055858)

**Pull request closed without merging**
