### PR TITLE
chore: parallel tests

### PR DESCRIPTION
**Pull request by parkjh**
`test:all` runs the following commands concurrently
- `lerna run lint --since -- -- --ci`
- `lerna run test --stream --since`
- `lerna run test:android --stream --since -- -- --ci --bail --coverage`
- `lerna run test:ios --stream --since -- -- --ci --bail --coverage`
- `lerna run test:web --stream --since -- -- --ci --bail --coverage`

### CODE REVIEW

**Comment by nathggns** [comment]
Do you have any stats for how well this improves things?

**Comment by parkjh** [comment]
@nathggns working on that

**Comment by parkjh** [comment]
@L0wry @shendriksen hey guys, how would I run this script on bitrise just for my pull request without affecting other builds?

**Comment by L0wry** [comment]
I can show you tomorrow!

**Comment by parkjh** [comment]
https://discuss.bitrise.io/t/parallel-builds-seperate-stacks-for-seperate-workflows-trigger-multiple-workflows-builds-at-the-same-time/410/25

**Pull request closed without merging**
