### PR TITLE
fix: storybook-native ios issue

### PR DESCRIPTION
**Pull request by killanaca**
Update the storybook-native ios with the latest changes related to react-native 0.50.1

### CODE REVIEW

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/3be064599a99d8518138ef4e7bcefb8337c7281f/dextrose-test/index.html

**Comment by nikhedonia** [comment]
We are almost there! We need to lockdown the react native version otherwise we'll might get this issue: 

screen shot 2018-02-15 at 18 37 39

**Comment by killanaca** [comment]
@nikhedonia no, I didn't. Could be related to some missed update of the Xcode SDK maybe?

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/6df629174ce5d5817ed9cb0f394efb7ac9b8fe34/dextrose-test/index.html

**Comment by nikhedonia** [comment]
as a side note, doesn't fix: https://github.com/facebook/react-native/issues/6627

**Pull request merged**
