### PR TITLE
[WIP] feat: native article provider

### PR DESCRIPTION
**Pull request by tuncaulubilge**
Flagged as WIP, as native part of this work is still in progress. The part in times-components can be reviewed.

- Split pages/article into a "simple article", which doesn't use a provider.
- Created "article from native" provider, which uses the native app as a data source for articles.
- Created a page in android-app, which uses the NativeProvider and renders a simple-article

### CODE REVIEW

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/44d4cc4cd18c673c0a949b38033c04a541929504/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/e8803be16af855dd3e86f20e8755c4a60c5424b4/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/b8b94934db74c5f121923ee683aceb3067368909/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/b8b94934db74c5f121923ee683aceb3067368909/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/ab1af3a7ef0deb9c99b64f1e4987f1b693be7142/index.html

**Comment by times-tools** [comment]
Please find visual snapshots of your changed components here: https://s3-eu-west-1.amazonaws.com/times-components-snaps/6737ef9ebd8891dbfcbb8beb40d35f382a8075a2/index.html

**Comment by craigbilner** [comment]
WIP

**Pull request closed without merging**
