### PR TITLE
Fix/watermark svg android perf

### PR DESCRIPTION
**Pull request by killanaca**
at the moment complex svg (like the watermark) take 8 sec to render on low end android devices (eg samsung s4). This PR create a specific (simpler) placeholder android component

screenshot_2017-11-14-17-27-12-5

### CODE REVIEW

**Comment by fampinheiro** [comment]
@killanaca is this being applied to every android device?

**Comment by killanaca** [comment]
@fampinheiro yes at the moment

**Comment by fampinheiro** [comment]
Could we do this just for screens that have a pixel ratio lesser than a sensible value? Don't like to level the experience with the crappiest device.

**Comment by craigbilner** [comment]
@fampinheiro @killanaca could we agree some metrics with which we "cut the mustard"?

**Comment by fampinheiro** [comment]
I am happy to merge it the way it is.
Let's just agree that we need to work on this as soon as we have the time.

**Pull request merged**
