### PR TITLE
chore: more descriptive pr template

### PR DESCRIPTION
**Pull request by parkjh**

### CODE REVIEW

**Comment by tuncaulubilge** [comment]
Personally, I'm not a big fan of PR templates, and quite happy with the current PRs

**Comment by nathggns** [comment]
I agree with @tuncaulubilge . Thanks for the effort of doing this @parkjh but unless a conversation among the team has happened in favour of this that I've missed, I think we should give this a miss.

**Comment by jimhunty** [comment]
This PR supports those who want to make contributions to the project outside of The Times. For those that don't know the internal standards and have the conversations we do. However, external contributions have been limited so far and until this gets promoted, this is unlikely to change. So for that reason, I don't think we should be having this for the time being.

**Comment by tuncaulubilge** [comment]
Three votes down, I'm closing the PR for now.

**Pull request closed without merging**
