### PR TITLE
chore: upgrade react native 0.60

### PR DESCRIPTION
**Pull request by parkjh**
Bumping from React Native 0.59.9 to latest (0.60)

Tasks:
- [ ] Bump RN, Jest, React, React-Native-Web, react-native-test-renderer to latest
- [ ] Update metro configs for app builds
- [ ] Update invalid accessibilityRoles as those are throwing errors on latest react-native
- [ ] Update gradle configuration on the android-app library bundle
- [ ] Update gradle configuration on the android storybook bundle
- [ ] Update metro configs for native storybooks
- [ ] Fix React-Native-Web issues
- [ ] Fix ios storybook issues 
- [ ] Integrate to the existing ios app (Need iOS dev assistance on this one)
- [ ] Fix broken tests (Jest update has some breaking changes, this might take time)

### CODE REVIEW

**Comment by parkjh** [comment]
@tuncaulubilge halp...

**Comment by parkjh** [comment]
https://github.com/react-native-community/rn-diff-purge/compare/release/0.59.9..release/0.60.0

**Comment by parkjh** [comment]
https://facebook.github.io/react-native/blog/2019/07/03/version-60

**Comment by tuncaulubilge** [comment]
Lol

**Comment by tuncaulubilge** [comment]
I'd suggest migrating to 0.59.10 first, as that has the latest JSC fixes in it.

**Comment by parkjh** [comment]
> I'd suggest migrating to 0.59.10 first, as that has the latest JSC fixes in it.

thanks @tuncaulubilge !

**Pull request closed without merging**
